TWILIO_SID = "ACbc2fdd2d2eb7263294f30f3b48d5d94c"
TWILIO_AUTH_TOKEN = "005080dd4ccc41977ce66850a590d38b"
WHATSAPP_TO = "whatsapp:+972525858990"
WHATSAPP_FROM = "whatsapp:+14155238886"
 
OPENAI_API_KEY = "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"
